name: My first workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
    - run: npm install
    - run: gulp build
    - uses: actions/upload-artifact@v4
      with:
        name: MyPackage
        path: dest
